# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 287e95b8415b66a5035deac8774022ec226ef3df2b0c8ec41c5171ed50bef3fd894bb4a6f6f04c33e937c93238609567be6adeb3b88d9dc22d5485baae7e04df

test:
  secret_key_base: 4d149d54d08f839f4289f843b26d306e2ea69578ac1d1a3b42175179a891b7e243e36ad752eddc3832590152f6b3597a76048b72c8dfe554d3ebb256ae25fb01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
